name: scheduled_test
version: 0.12.11+1
author: Dart Team <misc@dartlang.org>
description: This package is deprecated. See the README for details.
homepage: https://github.com/dart-lang/scheduled_test
environment:
  sdk: '>=1.22.0 <2.0.0'
dependencies:
  async: '^1.10.0'
  collection: '^1.5.0'
  http_multi_server: '>=1.0.0 <3.0.0'
  http: '>=0.9.0 <0.12.0'
  path: '>=0.9.0 <2.0.0'
  shelf: '>=0.5.2 <0.8.0'
  stack_trace: '>=0.9.1 <2.0.0'

  # Because scheduled_test exports test, it needs to keep its version constraint
  # tight to ensure that a constraint on scheduled_test properly constraints all
  # features it provides.
  test: '>=0.12.20 <0.12.21'
dev_dependencies:
  metatest: "^0.2.1"
  shelf_web_socket: "^0.2.0"
