name: scheduled_test
version: 0.12.5+5
author: Dart Team <misc@dartlang.org>
description: >
  A package for writing readable tests of asynchronous behavior.

  This package works by building up a queue of asynchronous tasks called a
  "schedule", then executing those tasks in order. This allows the tests to
  read like synchronous, linear code, despite executing asynchronously.

homepage: https://github.com/dart-lang/scheduled_test
environment:
  sdk: '>=1.16.0 <2.0.0'
dependencies:
  async: '^1.10.0'
  collection: '^1.5.0'
  http_multi_server: '>=1.0.0 <3.0.0'
  http: '>=0.9.0 <0.12.0'
  path: '>=0.9.0 <2.0.0'
  shelf: '>=0.5.2 <0.8.0'
  stack_trace: '>=0.9.1 <2.0.0'

  # Because scheduled_test exports test, it needs to keep its version constraint
  # tight to ensure that a constraint on scheduled_test properly constraints all
  # features it provides.
  test: '>=0.12.7 <0.12.14'
dev_dependencies:
  metatest: "^0.2.1"
  shelf_web_socket: "^0.2.0"
